if has("syntax")
  syntax on
endif

set ai
set hlsearch
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

" resize split with + and -
if bufwinnr(1)
    map + <C-W>+
    map - <C-W>-
endif

" Enter to exectute a php script
autocmd FileType php noremap <C-M> :w!<CR>:!/usr/bin/php %<CR>
autocmd FileType php noremap <C-L> :w!<CR>:!/usr/bin/php -l %<CR>

if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
endif
